import subprocess
import uuid
from pathlib import Path

from state import AgentOSState


def github_agent(state: AgentOSState) -> dict:
    run_id = uuid.uuid4().hex[:8]
    out_dir = Path("output") / run_id
    out_dir.mkdir(parents=True, exist_ok=True)
    for path, content in state["generated_code"].items():
        fp = out_dir / path
        fp.parent.mkdir(parents=True, exist_ok=True)
        fp.write_text(content, encoding="utf-8")

    branch = f"agentos-run-{run_id}"
    subprocess.run(["git", "checkout", "-b", branch], check=True)
    subprocess.run(["git", "add", str(out_dir)], check=True)
    subprocess.run(["git", "commit", "-m", f"feat: agentos generated run {run_id}"], check=True)
    subprocess.run(["git", "push", "-u", "origin", branch], check=True)
    pr = subprocess.run(
        [
            "gh", "pr", "create",
            "--title", f"AgentOS run {run_id}",
            "--body", "Auto-generated by AgenticOS MVP pipeline.",
            "--head", branch,
        ],
        check=True, capture_output=True, text=True,
    )
    pr_url = pr.stdout.strip().splitlines()[-1]
    subprocess.run(["git", "checkout", "master"], check=True)

    return {"github_pr_url": pr_url, "current_agent": "github_agent"}
